---
apiVersion: v1
kind: Namespace
metadata:
  name: kelos-system
  labels:
    app.kubernetes.io/name: kelos
    app.kubernetes.io/component: manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kelos-controller
  namespace: kelos-system
# BEGIN GENERATED: controller-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kelos-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kelos.dev
  resources:
  - agentconfigs
  - workspaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kelos.dev
  resources:
  - tasks
  - taskspawners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kelos.dev
  resources:
  - tasks/finalizers
  - taskspawners/finalizers
  verbs:
  - update
- apiGroups:
  - kelos.dev
  resources:
  - tasks/status
  - taskspawners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
# END GENERATED: controller-rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kelos-spawner-role
rules:
  - apiGroups:
      - kelos.dev
    resources:
      - taskspawners
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kelos.dev
    resources:
      - taskspawners/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - kelos.dev
    resources:
      - tasks
    verbs:
      - create
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kelos-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kelos-controller-role
subjects:
  - kind: ServiceAccount
    name: kelos-controller
    namespace: kelos-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kelos-leader-election-role
  namespace: kelos-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kelos-leader-election-rolebinding
  namespace: kelos-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kelos-leader-election-role
subjects:
  - kind: ServiceAccount
    name: kelos-controller
    namespace: kelos-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kelos-controller-manager
  namespace: kelos-system
  labels:
    app.kubernetes.io/name: kelos
    app.kubernetes.io/component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kelos
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kelos
        app.kubernetes.io/component: manager
    spec:
      serviceAccountName: kelos-controller
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: ghcr.io/kelos-dev/kelos-controller:latest
          args:
            - --leader-elect
            - --claude-code-image=ghcr.io/kelos-dev/claude-code:latest
            - --codex-image=ghcr.io/kelos-dev/codex:latest
            - --gemini-image=ghcr.io/kelos-dev/gemini:latest
            - --opencode-image=ghcr.io/kelos-dev/opencode:latest
            - --spawner-image=ghcr.io/kelos-dev/kelos-spawner:latest
            - --token-refresher-image=ghcr.io/kelos-dev/kelos-token-refresher:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kelos-telemetry
  namespace: kelos-system
  labels:
    app.kubernetes.io/name: kelos
    app.kubernetes.io/component: telemetry
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: kelos-controller
          securityContext:
            runAsNonRoot: true
          restartPolicy: OnFailure
          containers:
            - name: telemetry
              image: ghcr.io/kelos-dev/kelos-controller:latest
              args:
                - --telemetry-report
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              resources:
                limits:
                  cpu: 100m
                  memory: 64Mi
                requests:
                  cpu: 10m
                  memory: 32Mi
