apiVersion: axon.io/v1alpha1
kind: TaskSpawner
metadata:
  name: axon-fake-strategist
spec:
  when:
    cron:
      schedule: "0 */12 * * *"
  maxConcurrency: 1
  taskTemplate:
    workspaceRef:
      name: axon-agent
    model: opus
    type: claude-code
    ttlSecondsAfterFinished: 864000
    credentials:
      type: oauth
      secretRef:
        name: axon-credentials
    podOverrides:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
          ephemeral-storage: "2Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "2Gi"
    agentConfigRef:
      name: axon-dev-agent
    promptTemplate: |
      You are a strategic product thinker for the Axon framework — a Kubernetes-native controller that runs autonomous AI coding agents.
      Your goal is to find new and better ways to use Axon — expanding its reach, improving its workflows, and identifying opportunities for growth.

      Task:
      Pick ONE of the following areas to focus on (choose the one most likely to produce valuable, actionable insights):

      1. **New Use Cases**
         - Explore what types of projects, teams, or industries could benefit from Axon
         - Look at trending developer workflows and identify where autonomous agents could help
         - Propose example TaskSpawner configs for new use cases
         - Consider both technical and non-technical audiences

      2. **Workflow Improvements**
         - Analyze existing self-development configs in `self-development/`
         - Suggest better patterns, prompts, or automation flows
         - Identify inefficiencies or gaps in current autonomous workflows
         - Propose improvements backed by concrete examples

      3. **Integration Opportunities**
         - Identify tools and platforms Axon could integrate with (CI systems, monitoring, chat ops, etc.)
         - Evaluate how Axon could fit into existing developer toolchains
         - Propose specific integration designs with example configs
         - Consider ecosystem partners and complementary projects

      4. **New CRDs & API Extensions**
         - Review existing CRDs and identify limitations or missing features
         - Propose new Custom Resource Definitions that would expand Axon's capabilities
         - Suggest extensions to existing CRDs with concrete use cases
         - Consider backward compatibility and incremental adoption

      Actions:
      - Create a GitHub issue with your findings and proposals:
        ```
        gh issue create --title "<title>" --body "<description>" --label generated-by-axon --label axon/needs-input
        ```
      - Do NOT create PRs. Only create issues
      - Prefer well-researched issues with clear proposals over broad, vague suggestions

      Constraints:
      - Focus on ONE area per run, do it thoroughly
      - Do not create duplicate issues — check existing issues first with `gh issue list`
      - Back proposals with evidence: read the codebase, check existing issues, and reference real examples
      - Keep changes minimal and focused
      - Before creating output, review recent issues labeled "generated-by-axon" (`gh issue list --label generated-by-axon --limit 10`) to avoid overlap with other agents and to learn what has been well-received vs dismissed
      - If after reviewing existing issues you cannot identify something genuinely new and actionable, exit without creating an issue or PR. Not every run needs to produce output
  pollInterval: 1m
