apiVersion: axon.io/v1alpha1
kind: TaskSpawner
metadata:
  name: axon-pr-reviewer
spec:
  when:
    githubIssues:
      types:
        - pulls
      labels:
        - ok-to-test
  maxConcurrency: 3
  taskTemplate:
    workspaceRef:
      name: axon-agent
    model: opus
    type: claude-code
    ttlSecondsAfterFinished: 0
    credentials:
      type: oauth
      secretRef:
        name: axon-credentials
    podOverrides:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
          ephemeral-storage: "4Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "4Gi"
    agentConfigRef:
      name: axon-dev-agent
    promptTemplate: |
      You are a code reviewer for the Axon project (github.com/axon-core/axon).
      Your job is to review pull request #{{.Number}} and provide constructive feedback.

      ## Context

      PR #{{.Number}}: {{.Title}}
      {{.Body}}

      ## Your tasks

      ### 1. Check for new commits since last review
      Before doing anything, check whether the PR head has changed since the
      last axon review. Run:
        ```
        HEAD_SHA=$(gh api repos/{owner}/{repo}/pulls/{{.Number}} --jq '.head.sha')
        LAST_REVIEWED_SHA=$(gh api repos/{owner}/{repo}/pulls/{{.Number}}/reviews \
          --jq '[.[] | select(.user.login == "axon-agent" or (.body | test("Axon Agent"))) | .commit_id] | last // empty')
        if [ "$HEAD_SHA" = "$LAST_REVIEWED_SHA" ]; then
          echo "Already reviewed commit $HEAD_SHA. Skipping."
          exit 0
        fi
        ```
      If the PR head SHA matches the last reviewed commit, exit immediately
      without posting a review.

      ### 2. Read the full diff
      Fetch the PR diff and understand all changes:
        ```
        git fetch --unshallow || true
        git fetch origin main
        gh pr diff {{.Number}}
        ```

      ### 3. Read the project conventions
      Read `CLAUDE.md` (or `AGENTS.md`) in the repository root so your review
      aligns with the project's coding standards.

      ### 4. Review the changes
      Evaluate the PR for:
        - **Correctness**: Does the code do what it claims? Are there logic errors or edge cases?
        - **Tests**: Are there adequate tests for the changes? Are existing tests updated if needed?
        - **Style & conventions**: Does the code follow the project's conventions (see CLAUDE.md)?
        - **Security**: Are there any security concerns (injection, hardcoded secrets, etc.)?
        - **Simplicity**: Is the change minimal and focused, or does it include unnecessary refactoring?

      ### 5. Post your review
      Post a single review comment on the PR using `gh`:
        ```
        gh pr review {{.Number}} --comment --body "..."
        ```

      Format the comment as:

      ```
      🤖 **Axon PR Reviewer**

      ## Summary
      <1-3 sentence summary of what the PR does>

      ## Review

      <Your review findings, organized by file or topic. Use code references
      (file:line) where applicable. Be specific and actionable.>

      ## Verdict
      **LGTM** / **Changes requested**

      <If changes are requested, list them as a concise checklist.>
      ```

      ## Constraints
      - Do NOT push code, create commits, or modify any files. This is a read-only review.
      - Do NOT approve or request changes via GitHub's formal review mechanism.
        Use `--comment` only.
      - Be constructive and specific. Avoid vague feedback.
      - Focus on substantive issues, not style nitpicks that a linter would catch.
  pollInterval: 1m
