apiVersion: kelos.dev/v1alpha1
kind: TaskSpawner
metadata:
  name: kelos-triage
spec:
  when:
    githubIssues:
      types:
        - issues
      state: open
      labels:
        - needs-actor
      excludeLabels:
        - kelos/needs-input
  maxConcurrency: 8
  taskTemplate:
    workspaceRef:
      name: kelos-agent
    model: opus
    type: claude-code
    ttlSecondsAfterFinished: 3600
    credentials:
      type: oauth
      secretRef:
        name: kelos-credentials
    podOverrides:
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
          ephemeral-storage: "2Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
          ephemeral-storage: "2Gi"
    agentConfigRef:
      name: kelos-dev-agent
    promptTemplate: |
      You are a triage agent for the Kelos project (github.com/kelos-dev/kelos).
      Your job is to fully triage the following issue: classify it, check validity,
      assess priority, recommend an actor, and post a single triage comment using `gh`.

      ---
      Issue #{{.Number}}: {{.Title}}
      {{.Body}}
      {{if .Comments}}
      Comments:
      {{.Comments}}
      {{end}}
      ---

      ## Your tasks

      ### 1. Classify the issue
      Read the issue carefully and apply exactly one `kind/*` label:
        - `kind/bug` — something is broken or behaving incorrectly
        - `kind/feature` — a request for new functionality
        - `kind/api` — related to API changes or additions
        - `kind/docs` — documentation improvement or fix

      Apply the label:
        `gh issue edit {{.Number}} --add-label <kind-label> --remove-label needs-kind`

      ### 2. Check if already fixed
      Check whether this issue has already been resolved:
        - Search for merged PRs that reference this issue:
          `gh pr list --state merged --search "{{.Number}}" --limit 50 --json number,title,body`
        - Search recent commits on main for related changes:
          `git log --oneline -50 --grep="{{.Number}}"`
          `git log --oneline -50 --all-match --grep="<keywords from issue title>"`
        - Check the current codebase to see if the described problem still exists.
          Read the relevant source files and verify whether the reported behavior
          has been addressed.

      ### 3. Check if outdated or no longer relevant
      Determine whether the issue is outdated:
        - Does it reference APIs, flags, config fields, or features that no longer exist?
        - Does it reference old versions or dependencies that have since been upgraded?
        - Has the surrounding code been refactored or removed entirely?
        - Is the requested feature already implemented under a different name or approach?

      ### 4. Duplicate detection
      Search for other open issues that address the same thing:
        - `gh issue list --state open --limit 100 --json number,title,body,labels`
      Look for semantic overlap, not just title similarity. Flag every duplicate
      you find with its number and a one-line explanation of why they overlap.

      ### 5. Assess priority
      Based on your analysis, recommend a priority level:
        - `priority/important-soon` — Blocks adoption, user-facing bug, security issue,
          or directly requested by the maintainer
        - `priority/important-longterm` — Valuable improvement but not urgent, nice-to-have
          feature, or quality-of-life enhancement
        - `priority/backlog` — Low impact, speculative, or depends on other work

      Apply the label:
        `gh issue edit {{.Number}} --add-label <priority-label> --remove-label needs-priority`

      ### 6. Recommend actor
      Determine whether this issue can be handled autonomously by Kelos's worker agent:

      Assign `actor/kelos` if ALL of these are true:
        - The issue describes a concrete code change, documentation fix, test improvement,
          or configuration update with clear scope
        - The acceptance criteria are objectively verifiable (tests pass, docs are accurate,
          CLI output matches expectation, etc)
        - It does NOT require: new CRD design decisions, breaking API changes,
          infrastructure/cluster access, subjective design choices, or external service setup

      Leave `needs-actor` if ANY of these are true:
        - The issue requires architectural decisions or community input
        - The scope is ambiguous or open-ended
        - It depends on external systems Kelos cannot access
        - It requires human judgment about product direction

      If recommending `actor/kelos`:
        `gh issue edit {{.Number}} --add-label actor/kelos --remove-label needs-actor`

      ## Output
      Post exactly one comment on this issue using:
        `gh issue comment {{.Number}} --body "..."`

      Format the comment as:

      ```
      ## Kelos Triage Report

      **Kind**: <kind label applied>
      **Priority**: <priority label applied> — <one-line justification>
      **Actor**: `actor/kelos` or `needs human` — <one-line justification>

      **Status**: STILL VALID / ALREADY FIXED / OUTDATED / DUPLICATE

      **Evidence**:
      - <concise explanation of what you found, with links to relevant PRs, commits, or code>

      **Duplicates found**: #X (reason), #Y (reason) — or "None found"

      **Recommendation**: KEEP OPEN / CLOSE (with reason)
      ```

      After posting the comment, update labels to complete the triage lifecycle:
        `gh issue edit {{.Number}} --add-label triage-accepted --add-label kelos/needs-input --remove-label needs-triage`

      The `kelos/needs-input` label ensures a maintainer reviews before any worker
      agent picks up the issue. The maintainer can override priority or actor
      labels, then remove `kelos/needs-input` to approve.

      Do NOT open PRs, push code, or modify any files. Read-only analysis only
      (except for the comment and labels above).
  pollInterval: 1m
