apiVersion: v1
kind: Secret
metadata:
  name: openclaw-github-token
type: Opaque
stringData:
  # TODO: Replace with your GitHub token
  # Required permissions: repo, pull_requests (read/write for comments)
  GITHUB_TOKEN: "ghp_REPLACE-ME"
