apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
stringData:
  # TODO: Replace with your GitHub Personal Access Token
  # Get one at: https://github.com/settings/tokens/new
  # Required permissions: repo (for private repos), workflow (optional)
  GITHUB_TOKEN: "ghp_REPLACE-ME"
