apiVersion: v1
kind: Secret
metadata:
  name: anthropic-api-key
type: Opaque
stringData:
  # TODO: Replace with your Anthropic API key
  # Get one at: https://console.anthropic.com/settings/keys
  ANTHROPIC_API_KEY: "sk-ant-REPLACE-ME"
