{{- $sourceWebhooksEnabled := or .Values.webhookServer.sources.github.enabled .Values.webhookServer.sources.linear.enabled .Values.webhookServer.sources.gitlab.enabled .Values.webhookServer.sources.generic.enabled }}
{{- $gatewayServerEnabled := .Values.webhookServer.gatewayServer.enabled }}
{{- $gatewayServiceAccountName := .Values.webhookServer.gatewayServer.serviceAccountName }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kelos-controller
  namespace: kelos-system
{{- if or $sourceWebhooksEnabled (and $gatewayServerEnabled (eq $gatewayServiceAccountName "kelos-webhook")) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kelos-webhook
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if and $gatewayServerEnabled (ne $gatewayServiceAccountName "kelos-webhook") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $gatewayServiceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.slackServer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kelos-slack-server
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.consoleServer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kelos-console-server
  namespace: {{ .Release.Namespace }}
{{- end }}
